#! /bin/bash -f
SESSION_PY=/opt/clasp/lib/python3.7/site-packages/jupyter_client/session.py
#SESSION_PY=/usr/local/Cellar/ipython/6.5.0/libexec/vendor/lib/python3.7/site-packages/jupyter_client/session.py
echo "Looking for $SESSION_PY"
if [ -e $SESSION_PY ]
then
    ls -l $SESSION_PY
else
    echo "Could not find $SESSION_PY - do you have the correct python version?"
    exit 1
fi
if [ "$1" = "toggle" ]; then
 if [ -e $SESSION_PY.symlinked_away ]; then
     echo "Turning OFF jupyter debug"
     sudo rm $SESSION_PY
     sudo mv $SESSION_PY.symlinked_away $SESSION_PY
 else
     echo "Turning ON jupyter debug"
     sudo mv $SESSION_PY $SESSION_PY.symlinked_away
     sudo ln -s `pwd`/ipywidgets7.1/jupyter_client/session.py $SESSION_PY
 fi
fi
if [ -e $SESSION_PY.symlinked_away ]; then
    echo "jupyter debug ON"
else
    echo "jupyter debug OFF"
fi
